Added member Matej Antol and another affiliation at Masaryk University
bio-tools/biohackathon2022 pull request #15
Opened 2022-11-22 15:02 UTC by matejantol

2022-12-26 11:04 UTC, hmenager commented
Hi @matejantol, can you resolve the conflict in this PR? I'll be happy to merge it once it's done :smile:

2022-12-26 11:04 UTC, hmenager requested changes
Please revise to solve the conflict

2022-12-26 14:06 UTC, matejantol commented
Should be OK now :) thanks!

2023-02-15 07:15 UTC, hmenager approved these changes

2023-02-15 07:17 UTC, merged